apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-gateway.fullname" . }}
  namespace: {{ include "llm-gateway.namespace" . }}
  labels:
    {{- include "llm-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "llm-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-gateway.selectorLabels" . | nindent 8 }}
      {{- if or .Values.envConfig .Values.envSecret }}
      annotations:
        {{- if .Values.envConfig }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.envSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
          {{- if or .Values.envConfig .Values.envSecret }}
          envFrom:
            {{- if .Values.envConfig }}
            - configMapRef:
                name: {{ include "llm-gateway.fullname" . }}-config-env
            {{- end }}
            {{- if .Values.envSecret }}
            - secretRef:
                name: {{ include "llm-gateway.fullname" . }}-secret
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
