{{- if .Values.envSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-gateway.fullname" . }}-secret
  namespace: {{ include "llm-gateway.namespace" . }}
  labels:
    {{- include "llm-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.envSecret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}

