apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-gateway.fullname" . }}
  namespace: {{ include "llm-gateway.namespace" . }}
  labels:
    {{- include "llm-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "llm-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.envConfig.PORT }}
      targetPort: {{ .Values.envConfig.PORT }}
      protocol: TCP
